version: '3.9'

services:
  front-end-test:
    build:
      context: ../
    ports:
      - '3000:3000'
    environment:
      - VITE_PORT=3000
      - NODE_ENV=development
    volumes:
      - ../:/app
      - /app/node_modules
